webtalk_init -webtalk_dir C:/AB/Coding/verilog/project/RISC_V_PROCESSOR/riscvpro/riscvpro.sim/sim_1/behav/xsim/xsim.dir/msrv32_alu_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Aug 15 00:21:05 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9c40af70-9d4e-4be3-bdc0-b7e1770f1110" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7ea52c3ebfb54bec95d92dac61158e9f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "130 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8752_KB" -context "xsim\\usage"
webtalk_transmit -clientid 951083285 -regid "" -xml C:/AB/Coding/verilog/project/RISC_V_PROCESSOR/riscvpro/riscvpro.sim/sim_1/behav/xsim/xsim.dir/msrv32_alu_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/AB/Coding/verilog/project/RISC_V_PROCESSOR/riscvpro/riscvpro.sim/sim_1/behav/xsim/xsim.dir/msrv32_alu_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/AB/Coding/verilog/project/RISC_V_PROCESSOR/riscvpro/riscvpro.sim/sim_1/behav/xsim/xsim.dir/msrv32_alu_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
